### ISSUE TITLE
Train requirement

### ISSUE THREAD

**Issue by ShyWindddddd** [gemcollector/TLDA#1]
Could you please tell me how long the training has taken? Is there a high requirement on the memory of the graphics card? My 3080 is out of memory. QAQ ( 膜拜我们的清华大神呀~)

**Comment by gemcollector** [comment]
Hi, Wang~ It does need more compute resources due to calculating the Lipschitz constant for the pixels.  So your GPU should have enough memory. If you want to train the efficient generalizable agent on your 3080 machine, I think our recent work https://openreview.net/pdf?id=E-0zNz5J5BM can  realise it. The unofficial code is here: https://anonymous.4open.science/r/PIE-G-EF75. We will release a public version soon.

**Comment by ShyWindddddd** [comment]
Wow! Thanks for your patient reply to a newcomer in RL! Great to hear about your further research and I'd like to  continue to follow your work~
